site_name: GLIMPSE2
nav:
  - Home: index.md
repo_name: GLIMPSE2
repo_url: https://github.com/odelaneau/GLIMPSE
theme: 
  name: material
  color_mode: light
  logo: assets/images/branding/glimpse_logo_150x64.png
  favicon: assets/images/favicon.ico
  user_color_mode_toggle: false
  features:
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - content.footnote.tooltips
    - navigation.instant
    - navigation.instant.progress
    - navigation.instant.prefetch
    - navigation.footer
  font:
    text: Roboto
    code: Roboto Mono
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
  admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - abbr
  - attr_list
  - footnotes
  - pymdownx.blocks.caption
  - neoteroi.spantable
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde

extra_css:
  - assets/stylesheets/extra.css
  - assets/css/neoteroi-mkdocs.css
  - assets/css/header.css

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - glightbox
  - git-revision-date-localized:
      enable_creation_date: true